### ISSUE TITLE
X1turboでPCGの定義が上手くいかない

### ISSUE THREAD

**Issue by iromagenkutei** [medamap/CommonSourceCodeProject#10]
**不具合：**
X1turboでPCGの定義が上手くいかない

**再現手順：**
不具合を再現する手順:
1. X1センターさんのサイトにある高解像度対応パッチを導入したCZ8FB01を起動
2. 2枚目のスクショのプログラムを実行

**期待する動作：**
自機っぽい定義をしてる"Y"以外のフォントが青く定義される

**スクリーンショット：**
![Screenshot_20240326-073509](https://github.com/medamap/CommonSourceCodeProject/assets/164958638/d3599151-54dd-46da-afed-85d53716e6cb)

![Screenshot_20240326-103958~2](https://github.com/medamap/CommonSourceCodeProject/assets/164958638/4bc430fb-4f06-4216-9076-09158cc0205b)

**実行環境：**
- GitHubリリースバージョン： [V20240326]
 - デバイス: [例: AQUOS sense4 plus]
 - OS: [例: Android12]

**その他補足情報：**
今のところ不明

**Comment by medamap** [comment]
- 適用したものは [X1センター/ちょい技](http://www.x1center.org/x1tool/x1tips.html) の「X1用BASIC CZ-8FB01用自動HI RESO対応パッチ」と思われるのですが、概要を見た限りでは CRTC や PCG 定義に関する部分に手をいれているように見えます
- Android 版エミュレータは割とタイミング周りの動作が怪しそうなので PCG 定義に失敗している可能性があります
- CRTC 周りのタイミングに関する現象で調査して手を入れるにはかなりヘビーと思われます
- エミュレータの内部把握が全然進んでいないため、当分の間は保留といたします

**Comment by medamap** [comment]
## 修正対応
- ec11752 - テキスト縦２倍角と等倍を１行に混ぜたときの再現性を向上 / テキスト縦２倍角の右側にノイズが表示される不具合解消 / 20行、10行モードとテキストアンダーラインのサポート / ハイレゾ時、X1互換モードPCG定義の不具合解消

**Comment by medamap** [comment]
- [修正対応が確認された](https://twitter.com/stmlad/status/1776093182045872138) ため、この Issue をクローズします
