### ISSUE TITLE
他のアプリを選ぶと落ちる

### ISSUE THREAD

**Issue by yatyatyat1122** [medamap/CommonSourceCodeProject#14]
**不具合：**
他のアプリを選ぶと落ちる
BTキーボードの電源を落とすと落ちる
スリープすると落ちる

**再現手順：**
不具合を再現する手順:
1. 他のアプリを選ぶ
2. BTキーボードの電源0ff
3. 放置してスリープから復帰させると落ちてる

**期待する動作：**
落ちないようにする

**スクリーンショット：**
なし

**実行環境：**
- GitHubリリースバージョン： V20240328_check_apk
 - デバイス: Arrows/Google pixel共通
 - OS: Android11/14

**その他補足情報：**
なし

**Comment by medamap** [comment]
## 修正対応
- ab340c9 - 対応機種に PC-6001mk2SR を追加 / アプリ切り替え時にクラッシュする問題に対応

## 現在の状況
- BTキーボードを接続・切断でエミュレータ自体が再起動する現象がまだ残っている

**Comment by medamap** [comment]
- こちらの Issue はクローズして、BTキーボードの件について別 Issue で登録します
