### ISSUE TITLE
メディア選択ダイアログに表示されるファイル一覧のソート表示

### ISSUE THREAD

**Issue by medamap** [medamap/CommonSourceCodeProject#17]
**追加して欲しい機能の説明：**
- メディア選択時のファイル一覧をソート表示したい
- ソートオーダーはAからZへアルファベット順（昇順）にしたい

**追加要望の理由：**
- 現在メディア選択時のファイル一覧にはソートされていないため、ファイル数が多いと非常に選択しずらいため

**Comment by kirabee** [comment]
ファイル名でのソートとタイムスタンプでのソートとで切り替えができると助かります。例えば最近作成・追加したメディアを真っ先に選びたい場合とか。
ただし、もしもどちらか片方だけ実装するのならファイル名でのソートを優先した方が良いと思います。

**Comment by medamap** [comment]
- とりあえず、現時点でファイル一覧のソートができたため、この Issue はクローズします
- タイムスタンプについては必要であれば別途要望にて Issue をあげてもらえればと思います（基本、1 Issue につき 1 つでお願いします）
