### ISSUE TITLE
起動時に各種モードを変更できるようにしたい

### ISSUE THREAD

**Issue by medamap** [medamap/CommonSourceCodeProject#27]
**追加して欲しい機能の説明：**
- 機種毎に用意された様々なモードを設定変更し、起動できるようにする
- 機種によってはクロック切り替えスイッチがある
- X1 turbo のハイレゾ設定など
- 各機種毎の設定を調べて実装する

**追加要望の理由：**
- やっぱりないとダメでしょ的な

**Comment by kirabee** [comment]
各種モードの切り替えについてはほとんどが「上位機種において下位機種のソフトを実行する」際に必要な互換性を維持するための機能ですね。
下位機種版のエミュレータを実行すれば良いのでは？と思うかもしれませんが、上位機種しか所有していない人は下位機種用のROMを持っていないし上位機種版のROMを下位機種に流用することはたいていは失敗するので、モード切替は上位機種しかもっていない人がエミュレータで下位機種用のソフトを使う際に必要なんですよね。

**Comment by kirabee** [comment]
それとこれは未検証ですが、もしもAndroid版のエミュレータの初期設定が「下位機種に合わせた設定」であった場合、上位機種としての機能を封印した状態なので宝の持ち腐れになりますね。そして現状では初期値がどうなっているかを見ようにも該当するメニュー自体が未実装なので直ぐには分からない状態なのです。

**Comment by medamap** [comment]
- Win 版のメニューを移植し、各種設定が行えるようになったため、この Issue をクローズします
