### ISSUE TITLE
画面の整数倍スケーリングもしくはアンチエイリアスでの表示

### ISSUE THREAD

**Issue by X68000XVIcompact** [medamap/CommonSourceCodeProject#30]
追加して欲しい機能の説明：

・画面表示を整数倍スケーリング処理かアンチエイリアスで処理して欲しい

追加要望の理由：

・スマホの機種によりますが画面解像度が整数倍にならない機種では線の太さがまちまちとなり、
　タイリング表示などが美しくないためです

※表示不具合という訳ではありませんので、優先度は低くて大丈夫です。

**Comment by medamap** [comment]
- OpenGL に対応し、画面描画にバイリニアフィルタリングがかかるようになったので、以前より綺麗に表示されるようになりました、特に問題なければこの Issue はクローズします

**Comment by X68000XVIcompact** [comment]
最近確認遅れ気味ですいません、縦でも横でも綺麗なタイルで表示されるようになりました。
ご対応ありがとうございました！

**Comment by medamap** [comment]
- ご確認ありがとうございます、とりあえずこの Issue はクローズいたしますね
