### ISSUE TITLE
リセット時にモード選択ができるようにして欲しい

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#32]
**追加して欲しい機能の説明：**
1 リセット時にPC8801MAエミュレータと同様のモード選択を可能にして、リセット時に各種モードを指定可能にする機能
2 電源を切った状態で操作するスイッチ類や拡張ボード等の抜き差しはCONFIGで、電源を入れた状態で特定キー＋リセットによって選択可能なモード類は、この要望で実現するのが切り分けとして適していると思います
3 Issue #4 として既出であるスクリーンキーボードが消えない改善が実現するならば、この要望は不要です
4 Issue #27 に似た様な要望が挙がっていますが、こちらの要望(Issue #32)はリセット時に軽易かつ一時的に変更するための機能です
5 モード選択の項目に対して、各機種毎に何を実装した方が良いかは一概に言えないと思うので、これについては自分が分かる範囲で下に記載します
 (1)PC8001mk2の場合はNモードとN80モードの選択
 (2)PC8001mk2SRの場合はNモードとN80モードとN80SRモードの選択(エミュ自体はまだ未ビルドですが)
 (3)MSXの場合はDISKの切り離しの有無(ハード的には接続されているがソフト(BIOS)的には無効になっている状態)
 (4)上記(1)(2)(3)以外の機種についてはすみませんが分かりません。もしかしたら他機種にも同様のニーズがあるかもしれません
 (5)何をどう実装するか悩む場合は、いっそのことCONFIGのBootModeと同じ内容に合わせてしまうのもアリかと思います

**追加要望の理由：**
1 PC8001mk2はCTRLキーを押しながらリセットするとディップスイッチ(AndroidだとCONFIG)で指定したモードとは異なるモードで起動可能(NモードだとN80モード、N80モードだとNモード)であり、一時的にディップスイッチ(CONFIG)と異なる設定にしたい場合に使用する
2 MSXはFDD搭載機種の場合、SHIFTキーを押しながらリセットするとDISKを切り離し可能であり、DISK接続時に動かないソフトであっても動作可能
3 現状はキーを押しながらリセットできない為、特定のキー＋リセットでモードを切り替え可能な機種であってもAndroid版ではその機能が使えない(Windows版では可能、Android＋物理キーボードの場合は未検証)

**Comment by medamap** [comment]
- キーを押しながらリセットについては、ソフトキーボードでは実現できないため、一旦見送ります
- Bluetooth キーボードを使用した場合でも、そこは武田さんエミュレータではサポート範囲ではないのでこちらも見送ります
- Win 版から移植した拡張メニューにて起動時のモードが設定できるようになったため、そちらを利用する形でお願いします
- FD の切り離しについては、基本 1 つの Issue には 1 つの内容でお願いいたします（混在すると管理が煩雑になるため）
- 特にこのあと問題がなければ Issue をクローズします

**Comment by kirabee** [comment]
了解しました
FDの切り離しについては将来的にIssue #34の要望が実現したのちに、configメニューのデバイス選択の機能(FDのON/OFF)を確認してから必要なら改めて挙げるようにしますね

**Comment by medamap** [comment]
- 特に問題がなさそうなので Issue をクローズします
