### ISSUE TITLE
設定メニューにおいて今どの項目を選択済みなのかが分かるようにして欲しい

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#34]
**追加して欲しい機能の説明：**
設定メニューに対してWindows版と同様にアクティブな設定にはチェックマークなどの目印が付くようにして欲しい
ちなみにWindows版では複数項目の中から必ずどれか一つを選択する必要があるものは「黒丸」表記で、そうではなく各項目毎にON/OFF可能なものは「レ点」表記でアクティブか否かが判別できるようになっています
![1無題](https://github.com/medamap/CommonSourceCodeProject/assets/164736146/43b6f042-c14a-4217-b8ac-a777f2926242)
![2無題](https://github.com/medamap/CommonSourceCodeProject/assets/164736146/1714a338-3ad2-4268-b80a-928cf581b435)

**追加要望の理由：**
各エミュレータ毎の設定メニューが色々と追加されましたが、前回起動時(または初期値)にどの項目が選択されていて今どの項目がアクティブなのかが分からないのは不便なので追加して欲しいです

**Comment by medamap** [comment]
- この機能については現在実装方法について検討中ですが時間かかりそうです

**Comment by medamap** [comment]
- とりあえず選択済項目の色を濃くする事で対応しました、問題なければ Issue をクローズします
![image](https://github.com/medamap/CommonSourceCodeProject/assets/15664995/fca30665-7389-46a9-9f64-ed86c3f3cb4f)

**Comment by kirabee** [comment]
PC8801MAで以下の事が確認できました
・DeviceのBootで起動させるBASICのモード切り替えができて、その際に選んだものに色が付き、違うものを選ぶと色が戻る(排他選択)
・DeviceのCPUでクロックを切り替えられて、その際に選んだものに色が付き、違うものを選ぶと色が戻る(排他選択)
・ControlのRomaji to Kanaを選ぶとそれに色が付き、ローマ字入力中に再び選びなおすと色が戻る(トグル選択)
・DeviceのFloppy Driveで5インチのほかに8インチを追加できて、その際に5インチと8インチの両方を選択すると両方に色が付く(併用可能)
　ただし切り離しは現状ではできない(色付きのものを選択して色なしにしてもドライブアイコンは有効なまま)

たぶんFDDの切り離しは未実装だと思いますので、問題なく動作していますね
これで凄く見やすくなりました

**Comment by medamap** [comment]
- あれあれ、ドライブの切り離しってそこから出来たんですか、それは全然知らなかったですね
- とりあえず、メニューの表示機能としては実装できてるのでこれで Issue はクローズしたいと思います
