### ISSUE TITLE
ブランクテープの作成機能を追加して欲しい

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#35]
**追加して欲しい機能の説明：**
ブランクテープの作成機能を追加して欲しい。機能の細部については下記のとおりです
1 PC8001エミュレータにおいてWindows版では「CMT」→「rec」を選ぶとファイル名選択画面が表示される
2 ここで存在しないファイル名を入力するとサイズ0バイトのテープイメージのファイルが生成される
3 エミュレータ上で書き込み(CSAVE等)すると、テープイメージに対する書き込み用データが準備される
　(この段階では2で生成されたファイルのプロパティを見てもサイズは0のまま)
4 テープをイジェクトするかエミュレータを終了すると2で生成されたファイルに対し3で準備された内容が保存されてファイルがクローズされる
5 2～4の間はファイルがロックされていて他のプログラムから開くことは出来ないようになっている
6 他のエミュレータは未検証だが同様だと推測される
7 Android版では上記2の操作が実装されていないため、新規ブランクテープを作成できない

**追加要望の理由：**
既存のテープに追記するのは頭出し等の操作が必要となるから不便であるし、間違って上書きしてしまうと困るからテープファイルの保護という観点でもあまり望ましくないので、新規に作成したプログラムやゲームのセーブデータの保存には新規ブランクテープが必要である

※ファイルの削除、リネーム、移動等はWindowsではエミュレータでは行わずエクスプローラーで行っているが、Androidでも同様にエミュレータでなくファイラー等の別アプリで行うのが妥当だと思います

**Comment by medamap** [comment]
- ブランクテープ機能については実装されましたので、ご確認くださいませ

**Comment by kirabee** [comment]
ブランクテープの新規作成が出来ました。セーブとロードも問題ありませんでした。
ただしWindows版と違い、既存のテープファイルを選択しての追記が出来ないのは困る場面が、もしかしたらあるかもしれません。
ですがWindows版でテープファイルの分割や結合を行い、Androidでは必要最小限の使い方にするならそちらで作業すればOKですし、追記は諦めてテープ1、テープ2、テープ3みたいに分けてしまえば対処は可能ですから、現時点では困ってません
そもそも追記をするにはテープの早送りや頭出しの機能が新たに必要ですし
なので一応ご報告しましたが、自分としてはこれについては今のところは追加の改善は不要だと思います。

**Comment by medamap** [comment]
- 追記に関しては別件となるため、必要であれば新たに Issue 追加をお願いします
- このあと特にコメントがなければ Issue を閉じます

**Comment by kirabee** [comment]
わざわざ新規に挙げる必要は今のところありませんので、閉じてもらって問題ありません
もしも具体的に困る場面が多発した際には、改めて新規追加したいと思います

**Comment by medamap** [comment]
- Issue をクローズします
