### ISSUE TITLE
MZ -700,MZ -1500のSHIFT BRRAK

### ISSUE THREAD

**Issue by akd1500** [medamap/CommonSourceCodeProject#36]
**追加して欲しい機能の説明：**
MZ-700,MZ-1500でBREAKキーに割り当てられているキーが無いので、何か他のキーに割り当てて貰えると嬉しいです。
Win版ではBackSpaceキーに割り当てられています。

**追加要望の理由：**

SHIFT BREAKでBASICのプログラムなどを止められないです。

**Comment by shikarunochi** [comment]
MZ-700は、ESCキーにBREAKを割り当ててありますので、SHIFT+ESCで行けると思います〜。（Hacker'sKeyboardか外付けキーボードが必要です）
MZ-1500は未対応ですね。osd_input.cpp 内で機種ごとの割当を行っています。

**Comment by akd1500** [comment]
EmuZ-700でBREAKキーがESCに割り当てられているのを確認しました。
ありがとうございます。

**Comment by medamap** [comment]
- 特に問題なさそうなので Issue をクローズいたします
