### ISSUE TITLE
▼Exit時に自動で全デバイスEjectされない

### ISSUE THREAD

**Issue by yatyatyat1122** [medamap/CommonSourceCodeProject#37]
**不具合：**
▼ExitでOKしたら全デバイスEjectしてフラッシュしないと更新データロストする可能性が非常に高い。本家Windows版CSPはExitしたらセットされている全デバイスファイルがフラッシュされる

**再現手順：**
不具合を再現する手順:
1. データをセーブして▼をタップ
2. ExitのOKを選択
3. 再度実行してセーブデータの内容を確認

**期待する動作：**
セーブデータの内容が再実行後も一致する

**スクリーンショット：**
なし

**実行環境：**
- GitHubリリースバージョン： [V20240403_check]
 - デバイス: GooglePixel7
 - OS: [Android14]

**その他補足情報：**
なし

**Comment by medamap** [comment]
- [2024/04/05 テストリリース](https://twitter.com/Memme20000610/status/1776236460880146547) にて対応いたしました
- 一度ご確認いただければと思います

**Comment by medamap** [comment]
- 特に問題なさそうなので Issue をクローズします
