### ISSUE TITLE
キーを押しながらリセットする際にスクリーンキーボードが消えるため押し続ける事ができない

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#4]
PC-8001mk2においてN80モードとNモードはディップスイッチまたはCTRLキー+RESETで切り替え可能だが、前者は未実装であり後者はリセットしたらスクリーンキーボードが消えるため実行不可能である
これは同様の機能を持った他機種においても再現されると思われる

**再現手順：**
1. スクリーンキーボード(Hacker's Keyboard)を表示してCTRLキーを押しながらリセットアイコンを押す
2. スクリーンキーボードが消え、CTRLキーを押している状態がクリアされてしまう

**期待する動作：**
リセットを押してもスクリーンキーボードが消えず、CTRLキーを押し続けている場合はROMの初期化ルーチンが実行される際にCTRLキーを押している状態がプログラム側で認識されN-BASICとN80-BASICのどちらを起動するのかが切り替わる(ディップスイッチがNモードならN80モードに、N80モードならNモードに切り替わる、工場出荷時設定だと後者)
またはディップスイッチを実装する(Windows版のこのエミュではプルダウンメニューの[DEVICE]→[BOOT}にて実装されている。もちろんCTRL+リセットも可能)

**スクリーンショット：**
スクリーンショットがある場合は追加してください

**実行環境：**
 - デバイス: [ Xperia SO52B]
 - OS: [例: Android13]

**その他補足情報：**
RAM64Kバイトフル実装されたPC8001を使いたい場合、武田氏のPC8001エミュにはこの機能が実装されていないためPC8001mk2エミュをNモードで起動するしかなく、この切り替え機能は必要である
またSTOPキーを押しながらリセットするとホットスタート可能な機種においても同様の問題が生じると予想される

**Comment by shikarunochi** [comment]
PC-8801MAエミュレータは、リセット時にどのモードでリセットするか、ダイアログを出して選択できるようにしてますので、これと同じ感じで、リセットのタイミングで選択できるようにするのが良いのではないかと思います。
android_main.cpp の
selectBootMode と
Java_jp_matrix_shikarunochi_emulator_EmulatorActivity_bootSelectCallback あたりですね。

BOOT選択があるものがいくつかありますね。同じように対応できると思います。
![image](https://github.com/medamap/CommonSourceCodeProject/assets/38605844/adb52395-c8a7-48aa-bb85-141252d3e7e7)

**Comment by medamap** [comment]
- 現在では拡張メニューにて起動モードが選択できるようになったため、この Issue は特にコメント追記がなければクローズしたいと思います
- リセット画面での起動モード変更については機種毎に対応するとソースが肥大化するため、できれば廃止する方向にもっていきたいと思います

**Comment by medamap** [comment]
- 特にコメントがないためクローズします
