### ISSUE TITLE
Chromebookで全画面表示調整が効かない

### ISSUE THREAD

**Issue by NibblesLab** [medamap/CommonSourceCodeProject#42]
**不具合：**
Chromebookでの動作で、ウィンドウを全画面化した時に画面からあふれる

**再現手順：**
1. ウィンドウ右上の全画面表示アイコンをクリック
2. 表示自体は大きくなるが下があふれて見えない
3. 

**期待する動作：**
縦横の比率は守られるべきだが、相応の大きさで表示されてほしい

**スクリーンショット：**
スクリーンショットがある場合は追加してください

**実行環境：**
 - デバイス: Lenovo IdeaPad Duet
 - OS: ChromeOS 122.0.6261.137 Android11

**その他補足情報：**
表面的にはメニューが追加された時にコンフィグが無視されるようになったみたいに見える

**Comment by medamap** [comment]
- こちら Android 端末で動作させてみたのですが、下マージン機能は動いているのですが、そちらの環境ではマージンが有効化されてないということでしょうか？
- 下があふれて見えないというのは、最初の頃の表示に戻ったという理解であってますでしょうか？

**Comment by medamap** [comment]
- [以前作成した、別アプリのコンフィグ設定については設定ファイルの置き場所が変わりましたので使えなくなりました](https://twitter.com/Memme20000610/status/1775490150535209126)
- 最近追加した拡張メニューの HOST -> SCREEN -> SCREEN BOTTOM MARGIN から設定をお願いいたします

**Comment by NibblesLab** [comment]
確認しました。その説明を見てなかった…。

**Comment by medamap** [comment]
- 現在 Oh!石さんの環境では拡張メニューが使えない状態なので、まずはそちらのフリーズする問題を解決しないとこちらの確認は難しいと思います、まずはそちら潰していきたいところです

**Comment by medamap** [comment]
- [問題が解決された](https://twitter.com/oec_Nibbleslab/status/1778032552789561779) 事が確認されました
- この後特にコメントがなければ Issue をクローズします

**Comment by medamap** [comment]
- 問題なさそうなので Issue をクローズします
