### ISSUE TITLE
アイコンをタップすると落ちる

### ISSUE THREAD

**Issue by NibblesLab** [medamap/CommonSourceCodeProject#44]
**不具合：**
ファイル、メニュー、リセットなどアイコンをタップすると、アイコンに応じたダイアログが出て1秒ぐらいでエミュレータが落ちる。

**再現手順：**
不具合を再現する手順:
1.  エミュレータ起動
2.  フロッピーアイコンをタップ
3.  ディスクイメージ一覧の選択ダイアログが出る
4.  ほどなく落ちる

**期待する動作：**
正常に動作すること

**スクリーンショット：**
スクリーンショットがある場合は追加してください

**実行環境：**
- GitHubリリースバージョン： 応答がなくなるダイアログが出現するトラブルを解決するために試作ビルドされたX1turboエミュレータ
 - デバイス: 京セラ android One S8
 - OS: Android12

**その他補足情報：**
ログを取りました。
[logfile_kc.txt](https://github.com/medamap/CommonSourceCodeProject/files/14933464/logfile_kc.txt)

**Comment by medamap** [comment]
## ChatGPT4 による分析

- ログによると、クラッシュはメモリ割り当て中の「破損したチャンクヘッダー」によって発生しています。これはScudoによって識別されています。Scudoはメモリの破損や脆弱性を検出するために使用されるヒープメモリアロケーターです。

### ログからの主要な点は以下の通りです：

- SIGABRTシグナルによってクラッシュが引き起こされています。これは通常、プログラム自体がエラーを検出して中断したことを示します。
- Scudo ERROR: corrupted chunk header at address 0x200007517a25320というメッセージは、メモリの破損または誤用を示唆しており、二重解放や類似のメモリ管理エラーの可能性があります。
- エラーはアプリケーションjp.matrix.shikarunochi.emulator.x1turboのコンテキストで発生しました。
- この情報を踏まえて、以下の点を検討してください：

### メモリ管理：

- アプリケーション内のメモリの割り当てと解放の方法を確認してください。特にクラッシュが発生するエリアで、メモリの二重解放、解放後のメモリアクセス、バッファの境界を越えるアクセスなど、不適切なメモリアクセスを探してください。

### 並行処理の問題：

- アプリケーションが複数のスレッドを使用している場合、メモリの破損を避けるために共有リソースが適切に同期されていることを確認してください。

### ネイティブコード：
- NDKを使用しているので、ネイティブコードでのメモリ管理には細心の注意を払う必要があります。ネイティブコードのエラーは、管理されていないメモリ処理のため、Java/Kotlin側のエラーより追跡が困難になることがあります。

### テストと分析ツールの利用：
- メモリの破損問題を検出するために、AddressSanitizer（ASan）やValgrindなどのツールを活用してください。これらのツールは破損したメモリアクセスがどこで発生しているかを特定するのに役立ちます。

### 最近の変更のレビュー：
- このクラッシュが最近始まった場合、特にネイティブコードの部分でこの問題を導入した可能性がある最新の変更をレビューしてください。

- これらの側面に対処することで、クラッシュの原因を絞り込み、必要な修正を実装できます。

**Comment by medamap** [comment]
- [分析ツールを組み込んだ APK を作成してみました](https://52.gigafile.nu/0416-d4eba00cae8944ea9668fe204b1d7be8d)
- 上記 APK でクラッシュした時のログを確認し、そこから原因の個所を絞り込んでいきたいと思います
- お手数をおかけいたします、お時間あるときによろしくお願いいたします

**Comment by medamap** [comment]
- [メモリ範囲エラーの問題を解消しつつ、もし落ちたら詳細なログを出す APK を作成してみました](https://91.gigafile.nu/0511-c420e8476226b38a927f2f7a599d00a58)
- この APK で問題が発生しなくなる可能性もありますが、もち落ちるようならログの採取をお願いいたします
- Debug ビルド版なので、通常より重たい動作となります

**Comment by medamap** [comment]
- あらためて、もう一度 [分析ツールを組み込んだ APK を再作成しました](https://43.gigafile.nu/0416-25fa6ff3d845d272f1594bd6ddcf22ff)
- こちらはデバッグ版と、リリース版とあります
- ログの採取はデバッグ版のみ有効なので、デバッグ版でお願いいたします
- 分析ツール組み込み中に発見したメモリ境界エラーを解消してますので、ひょっとしたらもう直ってるかもしれません
- もし直っているのを確認したらリリース版の APK に差し替えてお楽しみください

**Comment by NibblesLab** [comment]
デバッグ版でログを取りました。
[logfile_kc2.txt](https://github.com/medamap/CommonSourceCodeProject/files/14945670/logfile_kc2.txt)
画面すら開かず落ちるようになりました。

**Comment by medamap** [comment]
- ログを確認いたしましたが、今回もメモリアクセス違反によるものですが、そもそもアプリの起動すらせず、アプリ固有のログも出力される前に落ちてしまってます
- 画面が落ちるのは分析ツールがメモリアクセス違反を検知してアボートさせています
- 今回のログは原因が発生した個所を特定が非常に困難です、ちょっと調査方法考えます
- とりあえずですが、リリース版の APK の方は試されたでしょうか？こちらは分析ツールが入ってないので起動と同時に落ちないと思うのですが、挙動とログがどう変わるかご確認いただけると助かります
- また今晩くらいにはログを大量に仕込んだ調査用の APK を用意したいと思います

**Comment by medamap** [comment]
- [ログを大量に仕込んだバージョンのAPK](https://92.gigafile.nu/0512-c3c448c05e023350e874b6115b5dc6706) を作成いたしました
- すぐにログのバッファがいっぱいになるかもですが、アイコンをタップした瞬間に落ちるとの事なので十分かなと思います
- またお手数をおかけしますがよろしくお願いいたします

**Comment by NibblesLab** [comment]
なぜか落ちずにちゃんと動くようになったんですが…。アイコンをタップしても落ちません。
ログを取りますか？

**Comment by medamap** [comment]
- それはまた不思議な現象が起きたものですね、ひょっとして処理のタイミングの問題の可能性もありそうです
- 念のため、ログをお願いできるようでしたら是非お願いいたします
- 昨日のテストリリースもついでに動作するか見ていただけると助かります

**Comment by NibblesLab** [comment]
ひとまず、動くようになったログを取りました。
[logfile_kc3.txt](https://github.com/medamap/CommonSourceCodeProject/files/14965560/logfile_kc3.txt)
起動してX1turboIIのデモディスクをセットしてデモが始まったらエミュレータを落としています。

**Comment by medamap** [comment]
- 確認しました、例外も出てないですし特に異常も見当たらない健康なログな印象をうけました
- これで最新のテストリリースの APK で問題が発生するようなら原因は端末の処理速度が早くて初期化が終わる前にどこか致命的な部分でメモリアクセス違反を起こしてる等の可能性もありえそうですね

**Comment by NibblesLab** [comment]
テストリリース版では問題ないようです。ちょっと気持ち悪いですがひとまず解決で良いと思います。

**Comment by medamap** [comment]
- 承知いたしました
- また再発しましたら新しく Issue の登録をよろしくお願いいたします
