### ISSUE TITLE
EmuZ-2200の名前がMZ-2200ではなくてMZ-2000になっている

### ISSUE THREAD

**Issue by kuran-kuran** [medamap/CommonSourceCodeProject#45]
**不具合：**
EmuZ-2200の名前がMZ-2200 emulatorではなくてMZ-2000 emulatorになっています。

**再現手順：**
不具合を再現する手順:
1. アンドロイドにインストールしてアイコンを確認するとMZ-2000 emulatorになっている

**期待する動作：**
アイコンの名前がMZ-2200 emulatorになるはず

**スクリーンショット：**

**実行環境：**
- GitHubリリースバージョン：V20240331A
 - デバイス: Xperia1
 - OS: Android11

**その他補足情報：**
ROMの置き場所は今のバージョンでもmz2200ROMになっていました。

**Comment by medamap** [comment]
- 今確認しました、とりあえず、名称を MZ-2200 emulator に変更いたしました
- 次回リリースでご確認ください
