### ISSUE TITLE
リセットアイコンからリセットができない

### ISSUE THREAD

**Issue by shikarunochi** [medamap/CommonSourceCodeProject#48]
**不具合：**
リセットアイコンを押したとき「ダブルクリックで選択」と表示されるが、ダブルクリックしてもリセットしない。

**再現手順：**
不具合を再現する手順:
1. リセットアイコンを押す

**期待する動作：**
ダブル繰区でリセットされる、もしくは リセット / キャンセル ボタンの選択表示にする。

**スクリーンショット：**
<img src="https://github.com/medamap/CommonSourceCodeProject/assets/38605844/aba08a39-1b24-4e6e-bbce-38eae9c2a26b" width="50%"/>

**実行環境：**
GitHubリリースバージョン： テストリリース 20240412
デバイス: Google Pixel 7
OS: Android 14

**その他補足情報：**
コントロールアイコン©のメニューからリセットを選択すればリセット可能です。
<img src="https://github.com/medamap/CommonSourceCodeProject/assets/38605844/e09f3782-7d20-4c9b-81b1-e0f2590327dc" width="50%"/>

**Comment by medamap** [comment]
- これはファイル選択ダイアログを改修した弊害ですね
- これはすぐ対応しておきたいと思います

**Comment by medamap** [comment]
- リセットできるように対応しました
- この後特にコメントがなければ Issue をクローズします

**Comment by shikarunochi** [comment]
ありがようございます。クローズお願いします。

**Comment by medamap** [comment]
- ご確認ありがとうございました！
