### ISSUE TITLE
インストール直後の初回起動時は必ずROMの読み込みに失敗する

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#5]
**不具合：**
始めてインストールしてアプリに権限が付与されていない状態でアクセス許可を出した場合、必ず起動に失敗するためアプリを一度終了して起動しなおす必要がある

**再現手順：**
不具合を再現する手順:
1. 初回インストール(アプリに権限が付与されていない状態)後に初起動する
2. 権限を付与するか否かの問い合わせが表示されるので許可する
3. ROMが無い状態でアプリが起動し操作できない

**期待する動作：**
権限を付与したらROMを読み込んで、そのまま正常に起動できること

**スクリーンショット：**
スクリーンショットがある場合は追加してください

**実行環境：**
 - デバイス: [例: Xperia SO52B]
 - OS: [例: Android13]

**その他補足情報：**
知っていれば実害は少ないが知らなければ動かないと断じられる恐れがあり、もったいないと思います

**Comment by medamap** [comment]
下記コミットにて対応が完了しました:
25c7109 - アクセス権限が付与されるまでエミュレータの起動を待機させる処理を追加

次回リリースにて APK に反映される予定です
