### ISSUE TITLE
Hacker's KeyboardでCTRLキーの押しっぱなしが出来ない

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#53]
**不具合：**
・PC8001系列とPC8801系列においてHacker's Keyboard使用時にCTRLキーを押しっぱなしにできない
・具体的には、CTRL+何かを押しっぱなしに出来ず、2文字目からCTRLを押している状態が解除されてしまう(例:CTRL+Gを押しっぱなしにするとBEEP音が鳴り続けるはずが、鳴るのは1回だけで後はgの文字が連続入力される)
・SHIFTキーは連続入力できている(SHIFT+Gを押しっぱなしにするとGの文字が連続入力される)
・Androidに109物理キーボードを接続した場合は発生せず、Windows版も発生しない

**期待する動作：**
CTRL+何かを同時押しし続けると、それ(コントロールコード)が正しく入力される
(CTRLを押しっぱなしにしている状態と他のキーを押しっぱなしにしている状態が同時に認識される)

**実行環境：**
- GitHubリリースバージョン： V20240415
 - デバイス: Xperia SO52B
 - OS: Android13

**その他補足情報：**
一応issueに書きましたがBASIC画面で何かを入力する際にコントロールコードを連打する事はほとんど無い(Breakキーが使用可能になったからCTRL+Cを連打する必要も無くなった)けれど、ゲーム等でCTRLキーに何かの機能が割り当てられていた場合に他のキー(テンキー等)との同時使用が出来ない恐れがあるのが気になります(CTRLキーを使用するゲーム等の具体例が直ぐに出てこないので未検証ですが、レアケースだと思うので優先度は低いですね)

**Comment by medamap** [comment]
- こちらのスマホで検証してみました
  - SHARP SH-01K で検証
  - Ctrl キーを押しっぱなしにして何かのキーの連打を行った場合、Ctrl キーの押下状態は維持される
  - Ctrl キーを押しっぱなしにして何かのキーを押しっぱなしにした場合、Ctrl キーの押下状態は解除される
- これは Hacker's keyboard の仕様なので、Hacker's keyboard の作者に問い合わせしてください
- 特になければこの Issue はクローズします

**Comment by kirabee** [comment]
了解しました。
