### ISSUE TITLE
MZ-1500のBrakeキー

### ISSUE THREAD

**Issue by akd1500** [medamap/CommonSourceCodeProject#54]
MZ-1500のBrakeキーに割り当てられているキーが無いです。
(MZ-700はESCキーに割り当てられています)

クローズされたのにしつこくてすみません

**Comment by medamap** [comment]
- すいません、見落としてました、MZ-1500 の Breke キーに相当するキーコードってわかりますでしょうか？

**Comment by akd1500** [comment]
すみません、よくわからないのですが、MZ-700と全く同じはずです。
1b?
https://github.com/medamap/CommonSourceCodeProject/issues/36#issuecomment-2036771600

**Comment by akd1500** [comment]
上のコメントの意味がわかっていないのですが、このあたりでしょうか。
![WS000201](https://github.com/medamap/CommonSourceCodeProject/assets/166001504/a051e815-1c67-4f26-b73b-5059190046c0)

**Comment by medamap** [comment]
- とりあえず、いれておいたので、また次回リリースで試してみてください

![image](https://github.com/medamap/CommonSourceCodeProject/assets/15664995/1c9b441f-e295-417b-8e0b-c283c4909e65)

**Comment by akd1500** [comment]
ありがとうございます♫

**Comment by medamap** [comment]
- 使ってもらって問題なければ Issue をクローズします

**Comment by akd1500** [comment]
了解しました。
対応していただき、ありがとうございましたm(_ _)m

**Comment by medamap** [comment]
- ご確認ありがとうございます、Issue をクローズしますね
