### ISSUE TITLE
キーボード表示中にタスク切り替えしてから戻るとキーボード表示とキーボードアイコンの状態が一致しなくなる

### ISSUE THREAD

**Issue by kirabee** [medamap/CommonSourceCodeProject#55]
**不具合：**
キーボード表示中にタスク切り替えしてから戻るとキーボードが消えるがアイコンはそのままとなり、その後はアイコン表示とキーボード表示がずれた状態になる

**再現手順：**
1. キーボードアイコンをONにしてキーボードを表示させる
2. タスク切り替えまたはアプリを最小化する
3. 再びアプリを表示させるとキーボードは消えるがアイコンはONのままとなる
4. これ以降はアイコンをOFFにするとキーボードが表示され、アイコンをONにするとキーボードが消える
5. 再びタスク切り替えまたはアプリを最小化した後にアプリを表示させると正常に戻る

**期待する動作：**
キーボード表示状態でタスク切り替えまたはアプリを最小化した後に再びアプリを表示させると、アイコンはONのままでキーボードも表示される
またはキーボードは消えてアイコンもOFFになる

**スクリーンショット：**

**実行環境：**
- GitHubリリースバージョン：  V20240419B
 - デバイス: Xperia SO52B
 - OS: Android13

**Comment by kirabee** [comment]
最新版で治ったのを確認できました
お疲れさまでした

**Comment by medamap** [comment]
- ご確認ありがとうございます、Issue 閉じますね
