### ISSUE TITLE
横画面にすると、画面描画が停止する

### ISSUE THREAD

**Issue by shikarunochi** [medamap/CommonSourceCodeProject#56]
**不具合：**
横画面にすると、画面描画が停止します。その後、縦画面に戻しても停止したままです。
プログラムは動作し続けていて、アイコンの操作などは可能です。

**再現手順：**
不具合を再現する手順:
1. 起動後に、横画面にする

**期待する動作：**
横画面が正しく描画される

**スクリーンショット：**
https://twitter.com/shikarunochi/status/1781346706053070850

**実行環境：**
- GitHubリリースバージョン： 20240419B
 - デバイス: Pixel 7
 - OS: Android 14 

**その他補足情報：**
デバッグバージョンを起動して横画面・縦画面変更を2回行って終了した時の logCat を添付します。

[x1_logcat_shikarunochi_20240420.txt](https://github.com/medamap/CommonSourceCodeProject/files/15046556/x1_logcat_shikarunochi_20240420.txt)

Galaxy Note 8（Android 9）では問題なく横画面になりましたので、機種による動作の違いと思われます。

**Comment by medamap** [comment]
- ありがとうございます、早速内容確認してみたいと思います！

**Comment by medamap** [comment]
- 原因としては画面回転時のサーフェイスの再作成に失敗しているようなので、それ用の対策と、あと、端末のスペック的に使用不可能な画面モードを使用している時は別な画面モードを使用する対策を入れ込んでみました
- これで動作すれば良いのですが、とりあえず次回リリースでまたお試しいただければ

**Comment by shikarunochi** [comment]
20240420A で、Pixel 7（Android 14）で横画面表示できました！ありがとうございます。

**Comment by medamap** [comment]
- いろいろな方から、横画面表示が出来たという報告もいただけたので、とりあえずこの Issue 閉じますね
- ご確認ありがとうございます
