### ISSUE TITLE
ローマ字入力機能が欲しい

### ISSUE THREAD

**Issue by gonzares-aaa** [medamap/CommonSourceCodeProject#6]
**追加して欲しい機能の説明：**
ローマ字入力が出来るようにして欲しい。

**追加要望の理由：**
エミュレータで、昔のアドベンチャーゲームをプレイしようとすると、カナ入力が必要なことが多い。
Androidのキーボードでは、カナ入力がサポートはされておらず、ゲームが遊べないため。

**Comment by medamap** [comment]
- ローマ字入力に対応しました
- ただし、機種によっては使用できないものもありますが、その場合は PC 版でもできないものは仕様となります
- 特にこのあとコメントがなければ Issue をクローズします

**Comment by gonzares-aaa** [comment]
X1,88MAで確認できました。
クローズしていただいて問題ございません。
ご対応ありがとうございました！

**Comment by medamap** [comment]
- ご確認ありがとうございます
- Issue をクローズします
