### ISSUE TITLE
Chromebookで全画面表示にならない

### ISSUE THREAD

**Issue by NibblesLab** [medamap/CommonSourceCodeProject#7]
**不具合：**
Chromebookでもエミュレータは動作するが、ウィンドウを全画面化しても実際の表示は全画面相当にならない。

**再現手順：**
1. ウィンドウ右上の全画面表示アイコンをクリック
2. 表示自体はそのままの大きさ
3. 

**期待する動作：**
縦横の比率は守られるべきだが、相応の大きさで表示されてほしい

**スクリーンショット：**
スクリーンショットがある場合は追加してください

**実行環境：**
 - デバイス: Lenovo IdeaPad Duet
 - OS: ChromeOS 122.0.6261.137 Android11

**その他補足情報：**

**Comment by medamap** [comment]
最新版で、横長のウインドウで横方向に長さを合わせて画面サイズを調整する改修が入りましたので、こちらのバージョンも一度お試しくださいませ
https://github.com/medamap/CommonSourceCodeProject/releases/tag/V20240325

**Comment by NibblesLab** [comment]
もうひとつ新しいV20200326Aで試したところ、かなり良い全画面表示になりました。使用しているエミュレータはMZ-2200です。
![image](https://github.com/medamap/CommonSourceCodeProject/assets/1759709/6bc936fa-3db0-425f-9d8e-19b4a3e8c8fa)
ただし、
・少し下にずれています(エミュ画面の8ドットくらい？)
・全画面表示のオン/オフでエミュレータが終了します(落ちている？これはこれで正常動作？)

**Comment by medamap** [comment]
- 全画面表示は右から２番目の画面モード切替のアイコンだと思うのですが、現在はそこはオミットされていて無反応にしてたはずなんですが、反応しちゃいました？後で確認してみます
- 次回のテストリリースで少し下に余白を開ける修正を入れてみたいと思います

**Comment by NibblesLab** [comment]
今回試している全画面表示は、ウィンドウの全画面切り替えアイコンを使用しています。Androidアプリではありますが、ウィンドウ表示される一般アプリみたいな扱いです(写真の、画面右上隅に×やら□やら、ウィンドウアプリでお馴染みの記号があるのが見えます)。
画面モード切り替えアイコンはちゃんと無反応になっています。

**Comment by medamap** [comment]
## 修正対応
- cb657de - 画面の縦と横切り替え処理を追加 / アイコンやキーボードタップ処理を画面切り替えに伴い修正
- 524fcce - 設定ファイル機能を復活 / 画面下マージン機能の追加
- 設定変更アプリにより、画面下にマージンを設定できるようになり、この問題は解決しましたので、クローズします

## 参考ツイート
- [Oh!石さんのツイート](https://twitter.com/oec_Nibbleslab/status/1774326443205620007)
![image](https://github.com/medamap/CommonSourceCodeProject/assets/15664995/f45edc5f-96d1-4f83-8a84-a681dde6eff3)
